{
  "hash": "772835bf8b080b8b16bf87351adfa123",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Computing Subthreshold Intervals\"\ndate: \"2026-09-29\"\ncategories: [code, analysis]\nimage: \"image.png\"\n---\n\n\n## Spoiler Alert\n\nCompute your NSM paces with the following Colab document:\n\n- [Colab](https://colab.research.google.com/drive/1E9gBvjxzVcup3U8bBR8GFGPCBGg5KL_o?usp=sharing)\n\n## A Note Before We Begin\n\nFor the sake of this post, we will assume, unreasonably, prior familiarity with the basics of the James Copeland's Norweigan Singles Method (`NSM`) and with Dr. Jack Daniels' formulation of `VDOT`. Absent that familiarity, I recommend the following books:\n\n- [*Norwegian Singles Method: Subthreshold Running Kept Simple*](Norwegian Singles Method: Subthreshold Running Kept Simple)\n- [*Daniels' Running Formula*](https://www.goodreads.com/en/book/show/112152.Daniels_Running_Formula)\n\nIf you don't have a library nearby, you can probably read more at the following websites, though you should, of course, still make some effort to support the relevant authors.\n\n- [Norwegian Singles Approach (NSA) Training Guide](https://www.reddit.com/r/NorwegianSinglesRun/wiki/index/)\n- [The Daniels/Gilbert Formula](https://www.simpsonassociatesinc.com/runningmath1.htm)\n\nIt's hard to know exactly how long any of those links will last, but here's hoping.\n\n## The Problem\n\nThere is one fundamental problem with the existing `NSM` formulations of which I am aware. In brief, to employ NSM, a runner would either need to (1) invest on the order of 100s of USD in a lactate monitor, or (2) rely on some other form of community-provided calculator. To my knowledge, there is one calculator of moderately high regard: LacTrace.\n\n- [LacTrace](https://lactrace.com/)\n\nTo the best of my knowledge, this tool was developed on a slight misinterpretation of early reported results from lactate testing. I believe, originally, three weekly intervals were recommended as follows:\n\n| Count | Duration, minutes | Pace, race distance |\n|-|-|-|\n|8-12 | 3-4   |  15k |\n| 4-6 | 6-8   | HM (~21k) |\n| 3   | 10-12 | 30k |\n\nHowever, we must note that these intervals were set, to the best of my knowledge, by James Copeland when James had an approximately 19 minute 5k. Consulting a third party VDOT calculator:\n\n- [VDOT Running Calculator](https://vdoto2.com/calculator)\n\nWe can plug in a 19 minute 5k and see the following race times.\n\n| Race Distance | Duration |  |\n|-|-|\n| 15k | 1:00:35   |\n| HM (~21k) | 1:27:14 |\n\nLike many calculators, this one does not report 30k times but if it did, it would report 2:06:56, and we'll see why latter.\n\n| Race Distance | Duration |  |\n|-|-|\n| 15k | 1:00:35   |\n| HM (~21k) | 1:27:14 |\n| 30k | 2:06:56 |\n\nThis corresponds to the following LacTrace intervals:\n\n| Duration, minutes | Pace, min/mi |\n|-|-|\n| 3-4   |  6:30-6:42 |\n| 6-8   | 6:39-6:51 |\n| 10-12 | 6:49-7:01 |\n\nWhat this just so happens to mean, is that James Copeland was running 3-4 minute intervals (I believe, in practice, 1km intervals, but that is neither here nor there), at a VDOT 60 minute pace, which we almost always, in training theory, regard as *threshold* pace.\n\nQuoth [*Runner's World*](https://www.runnersworld.com/advanced/a20807282/threshold-training/):\n\n> Most runners can figure that their threshold pace is equal to a pace they could race at for 50 to 60 minutes. In fact, for slower runners, threshold pace might actually be 10K race pace because they are taking nearly an hour to “race” this distance. Intensity of effort, not necessarily distance of running or racing, is what determines the degree of stress being put on the body’s systems.\n\nHold on, what was that?\n\n> Intensity of effort, not necessarily distance of running or racing...\n\nPulling the curtain back a little bit, we recall that the basis of `NSM` is sub-*threshold* training, not, perhaps, sub-15k training, and realize we may have a problem on our hands.\n\nIf we return to LacTrace and model, instead of a 19 minute 5k runner, a 60 minute 10k runner, we get the following paces:\n\n| Duration, minutes | Pace, min/mi |\n|-|-|\n| 3-4   | 9:55-10:11 |\n| 6-8   | 10:08-10:24 |\n| 10-12 | 10:19-10:35 |\n\nWe also note, at this time, that LacTrace does helpfully provide a threshold pace recommendation. For our 19 minute 5k runner, above, LacTrace reported a 6:33 *threshold* pace, squarely in the middle of the 3-4 minute interval pace. However, for a 60 minute 10k runner, it recommends a maximum 3-4 minute pace of 9:55 versus a 9:43 threshold pace. \n\nMy sense is that this recommendation would cause runners with a slower than 19 minute 5k to undertrain, runners with a 5k faster than 19 minutes to overtrain, and everyone without a 19 minute 5k to have a generally bad time, roughly in accordance with how close to 19 minutes they are.\n\nI understand a key goal of `NSM` is to achieve a sub-threshold *metabolic state*, rather than a physiological application specific to some race distance, so we need to create a calculator that instead determines 60, 90, and 120 minutes paces, rather than 15k, HM, and 30k. \n\nUnfortunately, existing VDOT tables, such as those in [*Daniels' Running Formula*](https://www.goodreads.com/en/book/show/112152.Daniels_Running_Formula), are all race-distance relative. Fortunately, I have a doctorate and no other hobbies.\n\n## The Mathematical Foundations of VDOT\n\n### Aside\n\nAs far as I know, these formulas are not present in any versions of [*Daniels' Running Formula*](https://www.goodreads.com/en/book/show/112152.Daniels_Running_Formula), and are instead on present in a specific edition of an earlier pamphlet named *Oxygen Power* (with a co-author named Gilbert), but I have yet to get access to *Oxygen Power* and am relying on third party sources, namely Larry Simpson's blog.\n\nLarry Simpson sets forth VDOT calculations in two parts: an oxygen cost for some velocity, and a maximum aerobic utilization for some duration.\n\n### Oxygen Cost\n\nThe Larry Simpson **Oxygen Cost Formula** over some velocity $v$, in meters per minute:\n\n$$\nO_2\\text{cost}(v) = 0.182258v + 0.000104v^2 - 4.6\n$$\n\nIt is a simple matter to express this in Python:\n\n::: {#4110e3a6 .cell execution_count=1}\n``` {.python .cell-code}\n# Larry Simpson Oxygen Cost Formula, attributed to Daniels/Gilbert\no_2_cost = lambda v : 0.182258 * v + 0.000104 * v * v - 4.6\n```\n:::\n\n\nI have never used meters per minute before, but in point of fact I do talk about a 19 minute 5k and not a, hold on...\n\n::: {#9a4d17b7 .cell execution_count=2}\n``` {.python .cell-code}\n# 19 minutes by 60 seconds per minute\nprint(19 * 60)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1140\n```\n:::\n:::\n\n\nRight - 1140 second 5k. A classic goal.\n\nFrom there, we can compute some oxygen costs:\n\n::: {#2ef15ac5 .cell execution_count=3}\n``` {.python .cell-code}\n# 40 minute 10k\nprint(\"40 min 10k:\", o_2_cost(10000/40))\n# 3 hour marathon\nprint(\"3 hr mara.:\", o_2_cost(42195 / (3 * 60)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n40 min 10k: 47.4645\n3 hr mara.: 43.83923488888888\n```\n:::\n:::\n\n\nAt this point, if you are a 41 minute 10k and 88 minute HM runner, like me, you probably realize something is wrong here. It is much harder to run a 3 hour marathon than a 40 minute 10k, yet the reported cost is lower. This isn't just me, our earlier [VDOT Running Calculator](https://vdoto2.com/calculator) agrees:\n\n| Race Distance | Duration |  |\n|-|-|\n| 10k | 0:40:00   |\n| Marathon | 3:04:43 |\n\nNot to worry, there's more to come.\n\n### Aerobic Utilization\n\nLarry Simpson calls this the \"drop dead formula\" which I find a bit morbid, but does capture the underlying truth that there is some physiological limit to pacing. I prefer to think of it as a maximum sustainable level of aerobic utilization. We imagine, for example, we can work harder for 1 minute than for 60 minutes. Larry Simpson presents the following, I believe also lifted from Daniels' *Oxygen Power*.\n\nAerobic Utilization, over some time $t$ in minutes:\n\n$$\nO_2\\text{util}(t) = 0.2989558e^{-0.1932605t} + 0.1894393e^{-0.012778t} + 0.8\n$$\n\nIt is a simple matter to express this in Python:\n\n::: {#be9c7cf3 .cell execution_count=4}\n``` {.python .cell-code}\n# We need the base of the natural logarithm, e\nfrom numpy import e\n# Larry Simpson Drop Dead Formula, attributed to Daniels/Gilbert\no_2_util = lambda t : 0.2989558 * e ** (t * -0.1932605) + 0.1894393 * e ** (t * -0.012778) + 0.8\n```\n:::\n\n\nWe can then ask, simply, what percentage of aerobic utilization can we sustain for, say, 1 hour - our threshold pace.\n\n::: {#154374ff .cell execution_count=5}\n``` {.python .cell-code}\n# Percentage Aerobic Utilization for One Hour (Threshold Pace)\nprint(o_2_util(60))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n0.8880073144800814\n```\n:::\n:::\n\n\nWe note, at this time, that this utilization is the same for all runners, regardless of pace. That is, threshold is set by duration, and the threshold pace corresponds to different race distance for different runners, from an elite half marathon, to a hobbyist 15k, to an athletic 10k, to a walking 5k.\n\nWe can now show just how we would find that runner with a 40 minute 10k would have around a 3:05 marathon.\n\nFirst, we compute the oxygen cost of a 40 minute 10k.\n\n::: {#2ad57c0b .cell execution_count=6}\n``` {.python .cell-code}\n# 40 minute 10k\ncost = o_2_cost(10000/40)\nprint(\"40 min 10k cost:\", cost)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n40 min 10k cost: 47.4645\n```\n:::\n:::\n\n\nSame as before.\n\nNow we compute the sustainable aerobic utilization for 40 minutes.\n\n::: {#a0a021de .cell execution_count=7}\n``` {.python .cell-code}\n# 40 minute utilization\nutil = o_2_util(40)\nprint(\"40 min use %age:\", util)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n40 min use %age: 0.9137614442697204\n```\n:::\n:::\n\n\nFrom here, we may finally compute the `VDOT`, a derived measure of distance-agostic running fitness. It roughly corresponds to an abstract idea of maximum, instanteous aerobic capacity.\n\n::: {#d89c15f3 .cell execution_count=8}\n``` {.python .cell-code}\n# 40min 10k VDOT\nvdot = cost / util\nprint(\"40 min 10k VDOT:\", vdot)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n40 min 10k VDOT: 51.9440826680247\n```\n:::\n:::\n\n\nAnd about that marathon...\n\n::: {#773a4266 .cell execution_count=9}\n``` {.python .cell-code}\n# 3 hour marathon VDOT\nprint(\"3 hour mar VDOT:\", o_2_cost(42195 / (3 * 60)) / o_2_util(3 * 60))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n3 hour mar VDOT: 53.52826876260377\n```\n:::\n:::\n\n\nWe can put it all together:\n\n::: {#fbcbcd9c .cell execution_count=10}\n``` {.python .cell-code}\n# VDOT given time in minutes and a distance in meters\nmarathon = 42195\nhalf_marathon = 42195 / 2\nvdot = lambda t, d : o_2_cost(d / t) / o_2_util(t)\n```\n:::\n\n\nAnd calculate, for example, the VDOT of a 19 minute 5k.\n\n::: {#c66f8e5b .cell execution_count=11}\n``` {.python .cell-code}\n# 19 minute 5k VDOT\nprint(vdot(19, 5000))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n52.880719428696324\n```\n:::\n:::\n\n\nSquarely between a 40 minute 10k and a 3 hour marathon, I might note.\n\n## The Solution\n\nSo we have now shown how to calculate VDOT (and do so over non-standard distances, such as 30k, by the way).\n\nIt remains, however, to calculate:\n\n1. The equivalent *pace*...\n2. For some *duration*...\n3. Based on some *race time*...\n4. For some *distance*.\n\nBasically, given some VDOT, how can we determine a sustainable 60 minute, 90 minute, and 120 minute pace. This is equivalent to determine the distance for those times as well (since we are fixing time), so essentially we are trying to solve the following, where $d$ is determined by interval duration and $d'$ and $t'$ are the distance and time of the most recent race result.\n\n$$\nd : \\text{VDOT}(t, d) = \\text{VDOT}(t', d')\n$$\n\nIt is a simple matter to expand `VDOT` back to its complete numerical expression:\n\n$$\n\\text{VDOT}(t, d) = \\frac{0.182258 \\times \\frac{d}{t} + 0.000104 \\times (\\frac{d}{t})^2 - 4.6}{0.2989558e^{-0.1932605t} + 0.1894393e^{-0.012778t} + 0.8}\n$$\n\nOr in Python:\n\n::: {#c7884625 .cell execution_count=12}\n``` {.python .cell-code}\n# VDOT given time in minutes and a distance in meters\nvdot = lambda t, d : (0.182258 * (d / t) + 0.000104 * (d / t) * (d / t) - 4.6) / (0.2989558 * e ** (t * -0.1932605) + 0.1894393 * e ** (t * -0.012778) + 0.8)\n```\n:::\n\n\nI suppose I can write that on more than one line.\n\n::: {#c0886da2 .cell execution_count=13}\n``` {.python .cell-code}\n# VDOT given time in minutes and a distance in meters\ndef vdot(t, d):\n    v = d / t\n    cost = (0.182258 * v + 0.000104 * v * v - 4.6)\n    util = 0.2989558 * e ** (t * -0.1932605) + 0.1894393 * e ** (t * -0.012778) + 0.8\n    return cost / util\n```\n:::\n\n\nWe then need only solve for $d$, a simple matter. You could, of course, think your own thoughts, but I prefer to use SymPy.\n\n::: {#f73ef7d4 .cell execution_count=14}\n``` {.python .cell-code}\n# Create variables for time and distance\nimport sympy\nt, d = sympy.symbols('t d')\n\n# Create a symbolic expression over these variables.\nexpr = vdot(t, d)\n\n# View the expression\nexpr\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=144}\n$\\displaystyle \\frac{\\frac{0.000104 d^{2}}{t^{2}} + \\frac{0.182258 d}{t} - 4.6}{0.8 + 0.2989558 {2.71828182845905}^{- 0.1932605 t} + 0.1894393 {2.71828182845905}^{- 0.012778 t}}$\n:::\n:::\n\n\nThe formatting is a bit different than what I did above manually, but you can probably convince yourself it's the same.\n\nWe take the existing example of a 19 minute 5k, which has... some VDOT.\n\n::: {#5b97c9c0 .cell execution_count=15}\n``` {.python .cell-code}\n# Set equal to the vdot of a 19 minute 5k\neq5k = sympy.Eq(expr, vdot(19, 5000))\neq5k\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=145}\n$\\displaystyle \\frac{\\frac{0.000104 d^{2}}{t^{2}} + \\frac{0.182258 d}{t} - 4.6}{0.8 + 0.2989558 {2.71828182845905}^{- 0.1932605 t} + 0.1894393 {2.71828182845905}^{- 0.012778 t}} = 52.8807194286963$\n:::\n:::\n\n\nAnd from there we can compute a distance to be covered in, say 120 minutes, previously regarded as the 30k pace.\n\n::: {#9313e817 .cell execution_count=16}\n``` {.python .cell-code}\n# Two hour distance for 19 minute 5k runner\nt = 120\ntwoh = sympy.Eq(vdot(t, d), vdot(19, 5000))\ntwoh\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=146}\n$\\displaystyle 8.58885744354709 \\cdot 10^{-9} d^{2} + 0.0018062168999377 d - 5.47044151019768 = 52.8807194286963$\n:::\n:::\n\n\nIt is a simple enough matter to solve for $d$.\n\n::: {#6309da4b .cell execution_count=17}\n``` {.python .cell-code}\n# Distance for a 2 hour run\ndist = sympy.solve(twoh, d)\ndist\n```\n\n::: {.cell-output .cell-output-display execution_count=147}\n```\n[-238753.116104769, 28455.4237970761]\n```\n:::\n:::\n\n\nFrom there, we can use our experience as runners to realize we rarely, if ever, run negative distances.  We got close to, but not exactly, 30k.\n\n::: {#7a97c1a4 .cell execution_count=18}\n``` {.python .cell-code}\n# Distance for a 2 hour run\ndist = [d for d in dist if d > 0][0]\ndist\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=148}\n$\\displaystyle 28455.4237970761$\n:::\n:::\n\n\nThis is probably more useful to us in minutes per mile, which I happen to use because of the uncommon misfortune of living in a country that places mile markers, rather than kilometre markers, on its race courses.\n\n::: {#d9304d3d .cell execution_count=19}\n``` {.python .cell-code}\n# There are 1609.344 m in a mi \n# https://en.wikipedia.org/wiki/Mile\nmi = 1609.344\npace = t / (dist / mi)\npace\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=149}\n$\\displaystyle 6.78680034348474$\n:::\n:::\n\n\nIn fairly obnoxious fashion, I also use seconds instead of fractional minutes.\n\n::: {#5ca0a294 .cell execution_count=20}\n``` {.python .cell-code}\npace // 1, pace % 1 * 60\n```\n\n::: {.cell-output .cell-output-display execution_count=150}\n```\n(6, 47.2080206090843)\n```\n:::\n:::\n\n\nWe can format that to look a bit nicer.\n\n::: {#e0d9bead .cell execution_count=21}\n``` {.python .cell-code}\n\"%02d:%02d\" % (pace // 1, pace % 1 * 60)\n```\n\n::: {.cell-output .cell-output-display execution_count=151}\n```\n'06:47'\n```\n:::\n:::\n\n\nSo for a 10 to 12 minute interval, a runner with a 19 minute 5k would run 6:47.  LacTrace is quite close to this, we recall:\n\n| Duration, minutes | Pace, min/mi |\n|-|-|\n| 3-4   | 6:30-6:42 |\n| 6-8   | 6:39-6:51 |\n| 10-12 | 6:49-7:01 |\n\nHowever, we can also check how our method stacks up for a (1) 13 minute 5k and (2) 30 minute 5k.\n\n### Putting it all together\n\nBefore that though, we took many tiny steps to get to our result. Let's wrap that up into one solution, shall we?\n\n::: {#f270e5ca .cell execution_count=22}\n``` {.python .cell-code}\n# Take \n#      a race time in minutes\n#      a race distance in meters \n#      a other time in minutes\n# Find the pace sustainable for that other time\n# In minutes per miles\n\ndef pace_finder(t_race, d_race, t_train):\n\n    # Libraries and unit conversions\n    from numpy import e\n    import sympy\n    mi = 1609.344\n    d = sympy.symbols('d')\n    \n    # VDOT calculator\n    def vdot(t, d):\n        v = d / t\n        cost = (0.182258 * v + 0.000104 * v * v - 4.6)\n        util = 0.2989558 * e ** (t * -0.1932605) + 0.1894393 * e ** (t * -0.012778) + 0.8\n        return cost / util\n        \n    expr = sympy.Eq(vdot(t_train, d), vdot(t_race, d_race)) \n    dist = sympy.solve(expr, d)\n    dist = [d for d in dist if d > 0][0]\n    pace = t_train / (dist / mi)\n    return pace\n```\n:::\n\n\nWe can \"pretty\" print the paces.\n\n::: {#1cdb8e29 .cell execution_count=23}\n``` {.python .cell-code}\n# Take \n#      a race time in minutes\n#      a race distance in meters \n# Print out intervals paces in minutes per mile.\ndef interval_finder(t, d):\n   show_pace = lambda p : print(\"%02d:%02d\" % (p // 1, p % 1 * 60))\n   show_pace(pace_finder(t, d, 60))\n   show_pace(pace_finder(t, d, 90))\n   show_pace(pace_finder(t, d, 120))\n```\n:::\n\n\nNow, training paces for someone with a 19 minute 5k.\n\n::: {#64184cf1 .cell execution_count=24}\n``` {.python .cell-code}\ninterval_finder(19, 5000)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n06:29\n06:39\n06:47\n```\n:::\n:::\n\n\nCompare to LacTrace:\n\n| Duration, minutes | LacTrace | Mine |\n|-|-|-|\n| 3-4   | 6:30-6:42 | 6:29 |\n| 6-8   | 6:39-6:51 | 6:39 |\n| 10-12 | 6:49-7:01 | 6:47 |\n\n### Seeing the Difference\n\nLet's consider a 13 minute 5k and a 30 minute 5k.\n\n::: {#a6a2ce4b .cell execution_count=25}\n``` {.python .cell-code}\ninterval_finder(13, 5000)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n04:32\n04:39\n04:45\n```\n:::\n:::\n\n\n| Duration, minutes | LacTrace | Mine |\n|-|-|-|\n| 3-4   | 4:27-4:35 | 04:32 |\n| 6-8   | 4:33-4:41 | 04:39 |\n| 10-12 | 4:39-4:47 | 04:45 |\n\n::: {#7e47b124 .cell execution_count=26}\n``` {.python .cell-code}\ninterval_finder(30, 5000)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n10:00\n10:16\n10:27\n```\n:::\n:::\n\n\n| Duration, minutes | LacTrace | Mine |\n|-|-|-|\n| 3-4   | 10:18-10:34 | 10:00 |\n| 6-8   | 10:32-10:48 | 10:16 |\n| 10-12 | 10:42-10:58 | 10:27 |\n\n## Use It Yourself\n\nWhile I had every intention of embedding a calculator here, that will have to be for another day, but you can run this code yourself in Google Colab or the Python environment of your choice.\n\n- [Colab](https://colab.research.google.com/drive/1E9gBvjxzVcup3U8bBR8GFGPCBGg5KL_o?usp=sharing)\n\nI currently have my most recent race, a 19:31 5k, at the beginning. \n\n```{.python filename=\"Colab Excerpt\"}\n# Your latest race result, in meters and minutes\nd = 5000\nt = 19 + (31/60)\n```\n\nSimply update the distance and time, and press the \"play\" button to the left. I get the following:\n\n```{.email filename=\"My NSM Paces\"}\n06:39\n06:50\n06:57\n```\n\n### The Usefulness\n\nSuppose you, as I do, know someone who recently ran a 02:25:40 half marathon.\n\n```{.python filename=\"Colab Excerpt\"}\nd = 21097.5\nt = 2 * 60 + 25 + (40/60)\n```\n\n| Duration, minutes | LacTrace | Mine |\n|-|-|-|\n| 3-4   | 10:52-11:08 | 10:32|\n| 6-8   | 11:05-11:21 | 10:48|\n| 10-12 | 11:16-11:32 | 10:59|\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}